databases:
 -  name: postgres
    ipAllowList: []
    databaseName: rails_on_render_production
    user: rails_on_render

services: 
  - type: web
    name: rails_on_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false